version: '3'
services:
  influxdb:
    image: influxdb 
    container_name: influxdb
    restart: unless-stopped
    network_mode: 'bridge'
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=speedtest
      - INFLUXDB_USER=influxdb
      - INFLUXDB_USER_PASSWORD=spdtst
    volumes:
      - influxdb:/var/lib/influxdb
  
  grafana:
    image: grafana/grafana:latest 
    container_name: grafana
    restart: unless-stopped
    network_mode: 'bridge'
    expose:
      - 3000
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ADMIN_PASSWORD=grafana_pwd
      - GF_AUTH_PROXY_AUTO_SIGN_UP=false
      - GF_AUTH_PROXY_ENABLED=true
    volumes:
      - grafana:/var/lib/grafana
    links:
      - influxdb:influxdb
    depends_on:
      - influxdb
      - speedtest
  
  speedtest:
    image: rpi-speedtest-cli
    container_name: speedtest
    restart: unless-stopped
    network_mode: 'bridge'
    environment:
      - TEST_INTERVAL=300
      - WRITE_CSV=False
      - WRITE_INFLUXDB=True
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_DB=speedtest
      - INFLUXDB_USER=influxdb
      - INFLUXDB_USER_PASSWORD=spdtst
    volumes:
      - speedtest:/var/lib/speedtest
    links:
      - influxdb
    depends_on:
      - influxdb
      
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - /home/pi/Documents/rpi-speedtest-cli/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    links:
     - grafana
    depends_on:
      - grafana

volumes:
  influxdb:
  grafana:
  speedtest:
